local.conf.sample: Disable wic
wic needs latest OE-core and dev is still on fido
until the dev moves to use morty or newer this
should be kept disabled fixes image build errors with fido

ERROR: No IMAGE_CMD defined for IMAGE_FSTYPES entry 'wic' - possibly invalid type name or missing support class

Signed-off-by: Khem Raj <raj.khem@gmail.com>